Adicionando AutoresDAO
faateodoro/NossaCasaDoCodigo pull request #2
Opened 2020-04-08 20:29 UTC by faateodoro

AutoresDAO criado e teste de verificação funcionando.

2020-04-09 14:19 UTC, wandersonmaceds requested changes

2020-04-09 14:19 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
> +        public static IList<Autor> Autores { get; set; }
Se é publico eu posso usar o atributo direto ao invés do método e cometer o deslize de apagar a lista inteira de uma vez simplesmente reatribuindo o valor para uma lista vazia, certo?

2020-04-09 14:19 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
> +            }
Me parece que você pode se livrar desse if se construir a lista direto no construtor.

2020-04-09 14:19 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
> +                    if (novoAutor.Email == autor.Email)
Aqui se o critério de igualdade do autor mudar para alguma outra coisa diferente do e-mail, a regra está em um lugar que não é o domínio do autor e por isso, você provavelmente sairia replicando essa regra em mais lugares que fosse preciso validar isso. Não?

2020-04-09 16:01 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
> +        public static IList<Autor> Autores { get; set; }
Certo, isso foi vacilo.

2020-04-09 16:20 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
> +            }
Coloquei no construtor e no teste chamo esse construtor sem atribuir em lugar nenhum.

2020-04-09 16:20 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
> +                    if (novoAutor.Email == autor.Email)
Quebrei esse método em dois. Um para comparar os emails e um para salvar o autor caso tudo esteja certo.

2020-04-09 16:51 UTC, wandersonmaceds requested changes

2020-04-09 16:51 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
> +        private static bool ComparaEmail(string email)
Aqui só movemos o problema do lugar, no Java, temos algo como o equals, no C# não temos algo parecido? Lembra, aqui é igualdade de objetos, a regra diz que o critério é o e-mail, mas ainda sim é comparação de objetos.

2020-04-20 13:24 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
> +        private static bool ComparaEmail(string email)
Método Equals sobrescrito e comparação refeita.

2020-04-20 20:16 UTC, wandersonmaceds requested changes

2020-04-20 20:16 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
>              }
Aqui, eu não queria acreditar que você precisaria fazer tudo isso na mão. E não precisa, assim como no java o Equals e esse laço para encontrar o novo autor podem ser implicitamente chamados quando você usa o método contains da própria ILIst. [Link da documentação](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist.contains?view=netframework-4.8#System_Collections_IList_Contains_System_Object_)

2020-04-20 20:31 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/AutoresDAO.cs
>              }
Estava usando o Contains de forma errada e realmente não iria funcionar daquele jeito. Resolvido.

2020-04-20 20:36 UTC, wandersonmaceds approved these changes

2020-04-22 17:50 UTC, merged