Visualiza livro
faateodoro/NossaCasaDoCodigo pull request #5
Opened 2020-06-10 22:52 UTC by faateodoro

Busca e visualização de livros feita. Fiz algumas refatorações, mas acredito que ainda vou limpar mais o código deixando a classe Program.cs apenas para executar o programa, provavelmente isolando o código dentro de uma classe dentro do projeto e repassando o código para limpar algo se precisar.

2020-06-12 12:26 UTC, wandersonmaceds requested changes

2020-06-12 12:26 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +        }
Funciona, mas acredito que a lista tem algum método que te ajude a retornar uma nova lista com os itens que você queira sem precisar de criar uma nova lista na mão. 

Aqui o nome do método não indica qual o critério da busca, pode passar a impressão de que posso passar qualquer coisa, ISBN, Resumo, etc.

2020-06-12 14:28 UTC, wandersonmaceds commented
Opa, esqueci de colocar no review, mas: salvar de Autor é void, os demais é string, por que existe essa divergência de retorno em métodos que fazem a mesma coisa?

2020-06-16 17:41 UTC, wandersonmaceds requested changes

2020-06-16 17:41 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +                .ToList();
Se o termo da busca não for em uppercase funciona?

2020-06-16 17:41 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +                .ToList();
Já vi no teste que você faz o toUpper antes de passar para a busca, quem garante que todo mundo vai fazer isso?

2020-06-17 12:19 UTC, wandersonmaceds requested changes

2020-06-17 12:19 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +                .Where(l => l.Titulo.Contains(busca, StringComparison.InvariantCultureIgnoreCase))
BOAAA!

2020-06-17 12:19 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/AutoresDAO.cs
> +            return $"Autor {novoAutor.Nome} foi cadastrado com sucesso!";
Confesso que já tenha visto que é incomum retornar strings indicando sucesso ou falha da operação. Esse tipo de estratégia é muito sensível, faz você trabalhar orientado a string.

2020-07-20 11:51 UTC, wandersonmaceds requested changes

2020-07-20 11:51 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/AutoresDAO.cs
> +            else
Aqui confesso duas coisas:

1 - Se a sua lista não deve ter objetos duplicados, alguma estrutura de dados já deve garantir isso para que você não precise checar isso na mão toda vez.

2 - Se o throw já está no fim do método, acredito que um early-return beneficia mais o seu programa do que ramificações de if-else: É bom lembrar que não é pra todo if que você precisa de um else.

2020-07-20 11:51 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/CategoriasDAO.cs
> +            if (!Buscar(novaCategoria))
Mesma coisa dos autores

2020-07-22 18:55 UTC, wandersonmaceds requested changes

2020-07-22 18:55 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/AutoresDAO.cs
> +            if (!Buscar(novoAutor))
Acho que aqui ficaria mais expressivo se fosse o contains direto. if(!Autores.Contains()), do que a busca, por que busca não busca de fato (de busca eu espero um retorno que seja diferente do que o um boleano), só diz se algo existe ou não.

2020-07-22 18:55 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/AutoresDAO.cs
> +            Autores = new HashSet<Autor>();
boa!

2020-07-22 18:55 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/CategoriasDAO.cs
> +            if (!Buscar(novaCategoria))
Mesma coisa da busca dos autores :)

2020-07-22 19:02 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/DAO/AutoresDAO.cs
> +            if (!Buscar(novoAutor))
Na verdade eu optei por fazer desse jeito, porque também uso na classe de testes. Mas tranquilo, posso alterar aqui e lá.

2020-07-23 16:50 UTC, wandersonmaceds approved these changes

2020-07-23 16:50 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/CategoriasDAO.cs
>          }
Aqui, se a lógica fosse inversa, throws no if, você evitaria a negação da lógica e esse return vazio em um método void seria evitado, deixando o código mais fácil de ler por que terá menos interpretações para serem feitas, mas você decide se quer deixar assim.

2020-07-24 12:20 UTC, merged

2020-07-24 12:21 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/DAO/CategoriasDAO.cs
>          }
Boa. Não tinha pensado nisso.
Vou alterar como primeiro commit do próximo card.