Vendas
faateodoro/NossaCasaDoCodigo pull request #6
Opened 2020-09-03 23:07 UTC by faateodoro

2020-09-04 18:08 UTC, wandersonmaceds requested changes

2020-09-04 18:08 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            new ProdutosDAO();
Não entendi, é uma instancia flutuante? Ela faz parecer que todas as chamadas nos outros métodos parecem ser estáticos.

2020-09-04 18:08 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            new ProdutosDAO();
Aqui você tá gerando um acoplamento muito forte do carrinho com o dao

2020-09-04 18:08 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +        }
Confesso que gostei da ideia de contar a quantidade de livros no estoque, mas isso não está descrito em nenhuma feature, a CDC por exemplo, imprime por demanda, então, não tem necessariamente um estoque. Talvez pensar no estoque tenha levado a solução mais complexa do que deveria.

2020-09-04 18:08 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +        }
Não é papel do carrinho buscar os produtos, ele apenas mantem uma lista do que selecionamos para a compra.

2020-09-04 18:08 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +        }
Esse método parece fazer sozinho muita coisa: calcula o total, imprime informações e ainda faz a lógica do if ali.

2020-09-04 18:08 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/CategoriasDAO.cs
> +            Console.WriteLine($"Categoria {novaCategoria.Nome} criada com sucesso!");
Gostei da inversão da lógica, mandou bem nessas refatorações.

2020-09-04 18:08 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/ProdutosDAO.cs
> +    public class ProdutosDAO
precisamos repensar essa classe por causa da ideia do estoque.

2020-09-04 18:16 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/DAO/ProdutosDAO.cs
> +    public class ProdutosDAO
Imaginei que pudesse ter alguns problemas com a complexidade que pensei para tudo isso. Com certeza vou revisar tudo o que foi dito, incluindo a ideia de descartar o estoque. Sei que isso não foi pedido, mas esse ponto não tinha pensado em impressão por demanda, devido ao background com logística: Tem estoque? Vende. Não tem? Marca o produto como fora de estoque.
Vou repensar nisso tudo e tentar limpar toda essa complexidade desnecessária.

2020-09-10 13:43 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/DAO/ProdutosDAO.cs
> +    public class ProdutosDAO
Removi completamente o conceito de estoque, tirei a dependência entre o Carrinho e ProdutosDAO, quebrei o método FinalizarCompra() em outros métodos. Tinha esquecido de mover a verificação se a quantidade de livros no carrinho era 1 ou maior, mas fiz mais um commit.

2020-09-10 13:45 UTC, wandersonmaceds requested changes

2020-09-10 13:45 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            NumeroEhValido(quantidade);
Confesso que não achei necessário este método, ele é um if tão simples. Se esse if foi extraído para um método, por que o if do livro = null, também não foi?

2020-09-10 13:45 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            MostrarLivrosNoCarrinho();
Acho que essas extrações não valem a pena, elas não são difíceis de ler, aliás, por que tudo estático?

2020-09-10 13:51 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            NumeroEhValido(quantidade);
O tipo int não pode ser nulo. O valor padrão é 0.

2020-09-10 14:03 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            NumeroEhValido(quantidade);
Fiz um teste e uma variável int não pode receber null a menos que seja declarado int?

2020-09-10 14:06 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            MostrarLivrosNoCarrinho();
As extrações foram feitas, porque foi avaliado anteriormente que o método fazia tarefas demais. Agora ele chama os métodos que compõem a finalização da compra.
Quanto a tudo ser estático, concordo que não me atentei. Sempre que é feita a refatoração pela a IDE os métodos são gerados como estáticos. Alterado.

2020-09-10 17:07 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            MostrarLivrosNoCarrinho();
Mas você naturalmente havia removido coisas, quando removeu o estoque. Extração por causa de um if simples não é a ideia.

2020-09-10 17:09 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            MostrarLivrosNoCarrinho();
tá certo.

2020-09-10 17:13 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/CarrinhoDeCompra.cs
> +            MostrarLivrosNoCarrinho();
Código simplificado.

2020-09-10 17:14 UTC, wandersonmaceds approved these changes

2020-09-10 17:25 UTC, merged