Adicionando novos teste na aplicação
faateodoro/NossaCasaDoCodigo pull request #7
Opened 2020-10-07 15:19 UTC by faateodoro

Adicionei/alterei alguns testes e também corrigi alguns pontos que estavam inconsistentes.

2020-10-13 13:46 UTC, wandersonmaceds requested changes

2020-10-13 13:46 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +                throw new NullReferenceException("A busca não pode ser nula!");
Acho que a ordem importa, não? se você verifica por nulo depois de fazer um trim, vai ter um NullReferenceException no primeiro if, correto?

2020-10-13 13:46 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +            if (Livros.Contains(novoLivro) && Livros.Count > 0)
Aqui eu não sei se entendi, você precisa mesmo chegar se o tamanho da lista é maior que zero? Acredito que o contains vai ver que a lista está vazia e dar false logo de cara.

2020-10-14 13:55 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +            if (Livros.Contains(novoLivro) && Livros.Count > 0)
Realmente, foi um teste besta que fiz e esqueci de desfazer isso. =/

2020-10-14 16:07 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +        public static IList<Livro> MostrarLivrosBuscados(string busca)
Por que todos os métodos da sua classe são estáticos?

2020-10-14 16:07 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Testes/TestaCarrinho.cs
>          private static CarrinhoDeCompra Carrinho = new CarrinhoDeCompra();
por que seus atributos são estáticos?

2020-10-14 16:07 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Testes/TestaCarrinho.cs
> +                    new object[]{"Titulo Novo", LivrosHelpers.RESUMO_COM_MAIS_DE_500_CARACTERES, "Teste", 20, "978-12-34567-89-0",
Se você tem a entidade Livro, por que daria new em um object?

2020-10-14 16:07 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Testes/TestaVisualizacaoLivros.cs
> +        private static void CadastrarAutoresDao()
existe algum motivo especial pra esses statics aqui?

2020-10-20 20:23 UTC, faateodoro commented on NossaCasaDoCodigo.Testes/TestaCarrinho.cs
> +                    new object[]{"Titulo Novo", LivrosHelpers.RESUMO_COM_MAIS_DE_500_CARACTERES, "Teste", 20, "978-12-34567-89-0",
Então, já tinha feito um teste com isso e refiz para ter certeza. Fiz esse objeto com Livro[], mas na hora de passar o teste com a linha `[MemberData(nameof(TeoriasInvalidasISBN))]` exige um `IEnumerable<object[]>`.
Outro ponto é que todos os códigos de exemplo (documentação, posts e Stack Overflow) sempre utilizam `IEnumerable<object[]>`.

2020-10-20 20:32 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +        public static IList<Livro> MostrarLivrosBuscados(string busca)
A chamada do teste quebra sem o static. Também ocorre na classe Program.cs

2020-10-20 20:35 UTC, faateodoro commented on NossaCasaDoCodigo.Testes/TestaVisualizacaoLivros.cs
> +        private static void CadastrarAutoresDao()
Esses métodos estáticos dessa classe foram extraídos e o VS extrai como estáticos. Corrigido.

2020-10-20 20:44 UTC, faateodoro commented on NossaCasaDoCodigo.Testes/TestaCarrinho.cs
>          private static CarrinhoDeCompra Carrinho = new CarrinhoDeCompra();
Neste caso foi uma boa pergunta. Alterado.

2020-10-22 11:40 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +        public static IList<Livro> MostrarLivrosBuscados(string busca)
Conseguiu fazer funcionar sem o static no commit?

2020-10-22 11:41 UTC, wandersonmaceds commented on NossaCasaDoCodigo.Testes/TestaCarrinho.cs
> +                    new object[]{"Titulo Novo", LivrosHelpers.RESUMO_COM_MAIS_DE_500_CARACTERES, "Teste", 20, "978-12-34567-89-0",
Usar object não é tão ruim, se a ferramenta te força a isso, é uma forma dela tentar um polimorfismo da forma mais abstrata possível, mas se ela tiver suporte a algum generic, por que não tentar?

2020-10-22 12:20 UTC, faateodoro commented on NossaCasaDoCodigo.Testes/TestaCarrinho.cs
> +                    new object[]{"Titulo Novo", LivrosHelpers.RESUMO_COM_MAIS_DE_500_CARACTERES, "Teste", 20, "978-12-34567-89-0",
Tentei IEnumerable<Livro> e sem sucesso também. A ferramenta quer IEnumerable<Object[]>.

2020-10-22 12:21 UTC, faateodoro commented on NossaCasaDoCodigo.Biblioteca/DAO/LivrosDAO.cs
> +        public static IList<Livro> MostrarLivrosBuscados(string busca)
Feito.

2020-10-27 13:07 UTC, merged